version: "3.9"
services:
  mysql_db:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hakimlivs

  api_service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql_db
    depends_on:
      - mysql_db